---

- name: unload nouveau
  modprobe:
    name: nouveau
    state: absent
  ignore_errors: true

- name: Add NVIDIA package signing key
  ansible.builtin.apt_key:
    url: https://nvidia.github.io/libnvidia-container/gpgkey

- name: Install packages for interacting with s3 endpoint
  become: true
  ansible.builtin.apt:
    pkg:
      - python3
      - python3-boto3
      - python3-botocore

- name: Install packages for building NVIDIA driver kernel module
  become: true
  ansible.builtin.apt:
    pkg:
      - build-essential
      - wget
      - dkms

- name: Make /etc/nvidia/ClientConfigToken directory
  become: true
  file:
    path: /etc/nvidia/ClientConfigToken
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Download NVIDIA License Token
  amazon.aws.s3_object:
    endpoint_url: "{{ nvidia_s3_url }}"
    access_key: "{{ nvidia_bucket_access }}"
    secret_key: "{{ nvidia_bucket_secret }}"
    bucket: "{{ nvidia_bucket }}"
    object: "{{ nvidia_tok_location }}"
    dest: /etc/nvidia/ClientConfigToken/client_configuration_token.tok
    mode: get

- name: Set Permissions of NVIDIA License Token
  file:
    path: /etc/nvidia/ClientConfigToken/client_configuration_token.tok
    state: file
    owner: root
    group: root
    mode: 0744

- name: Download NVIDIA driver
  amazon.aws.s3_object:
    endpoint_url: "{{ nvidia_s3_url }}"
    access_key: "{{ nvidia_bucket_access }}"
    secret_key: "{{ nvidia_bucket_secret }}"
    bucket: "{{ nvidia_bucket }}"
    object: "{{ nvidia_installer_location }}"
    dest: /tmp/NVIDIA-Linux-grid.run
    mode: get

- name: Set Permissions of NVIDIA driver
  file:
    path: /tmp/NVIDIA-Linux-grid.run
    state: file
    owner: root
    group: root
    mode: 0755

- name: Install NVIDIA driver
  become: true
  ansible.builtin.command:
    argv:
      - "sh"
      - "/tmp/NVIDIA-Linux-grid.run"
      - "-s"
      - "--dkms"
      - "--no-cc-version-check"

- name: Create GRIDD licensing config
  become: true
  template:
    src: templates/gridd.conf.j2
    dest: /etc/nvidia/gridd.conf
    mode: 0644

- name: Cleanup packages for interacting with s3 endpoint
  become: true
  ansible.builtin.apt:
    state: absent
    purge: true
    pkg:
      - python3-boto3
      - python3-botocore