apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/kubernetes-sigs/cluster-api-provider-azure/releases/download/v1.10.2/cluster-template-windows.yaml
patchesStrategicMerge:
- ../patches/azuremachinetemplate-windows.yaml
- ../patches/kubeadmcontrolplane-windows.yaml
- ../patches/machinedeployment-windows.yaml